### ISSUE TITLE
Ladeleistung wird nur kurzzeitig geändert.

### ISSUE THREAD

**Issue by Bjoern79** [foxriver76/ioBroker.sonnen#118]
Die Ladeleistung wird zurückgesetzt.

nach dem Ändern des DP Control.charge wird der neue Sollwert von der Batterie übernommen allerdings nur für ca. 20 Sekunden. Der geänderte Wert im Datenpunkt bleibt erhalten.
Vielleicht gibt es dazu schon Erfahrungen.

**Versions:**
 - Adapter version: 1.9.8
 - Battery model: Eco8
 - Raspberry:
 PlatformBetriebssystem:linux
Architektur:arm
CPUs:4
Geschwindigkeit:1500 MHz
Modell:ARMv7 Processor rev 3 (v7l)
RAM:3.7 GB
System-Betriebszeit:47 T. 22:28:36
Node.js:v14.18.1
NPM:6.14.15
Datenträgergröße:58.4 GB
Festplatte frei:42.9 GB
Adapter-Anzahl:405
Betriebszeit:47 T. 22:35:07
Aktive Instanzen:18
Pfad:/opt/iobroker/

**Comment by foxriver76** [comment]
Der Wert ist write only, Aktualisierungen von der Batterie kommen da nicht. Verhalten ist bei mir genauso, gehe aber davon aus dass es an der Sonnen flat liegt, die es wohl nicht erlaubt das selbst zu steuern.

**Comment by Bjoern79** [comment]
Vielen Dank für die Rückmeldung.
Ich habe mal eine Service Ticket zu dem Thema bei Sonnen eröffnet. Mal schauen was dabei rauskommt.

**Comment by foxriver76** [comment]
Bin gespannt was dabei rum kommt. ;-)

**Comment by MoerserFisch** [comment]
Über die lokale Benutzeroberfläche der Sonnenbatterie muss erst noch zugelassen werden, dass Werte geschrieben werden können. Dort ist auch der API-Key auffindbar.
![Screenshot 2022-04-30 172902](https://user-images.githubusercontent.com/91428978/166111993-bd95182e-196f-431a-af68-18aaaba08b51.png)
.

**Comment by skyx3** [comment]
Hi ich würde die Option gern verstehen. Was genau wird damit gesteuert. Discharge wie weit der Akku entladen werden darf (Notstrom) und charge wie weit er aufgeladen werden darf z.B. max 90% ODER geht es bei der Option darum wieviel Watt maximal be- und entladen werden darf. Also z.B. das Haus brauch 2.000 Watt gerade und ich stelle Discharge auf 1.000 Watt, würde er dann nur 1.000 Watt ziehen und die übrigen Energie direkt aus dem Netz?

**Comment by foxriver76** [comment]
> Also z.B. das Haus brauch 2.000 Watt gerade und ich stelle Discharge auf 1.000 Watt, würde er dann nur 1.000 Watt ziehen und die übrige Energie direkt aus dem Netz?

So verstehe ich das.

**Comment by skyx3** [comment]
OK dann war das Mist mit den 1000W, wie könnte ich das rückgängig machen, einfach auf 7000 Watt stellen, das wäre ja die Max Entladeleistung.

**Comment by CharlesPerley** [comment]
> OK dann war das Mist mit den 1000W, wie könnte ich das rückgängig machen, einfach auf 7000 Watt stellen, das wäre ja die Max Entladeleistung.

also bei meinen test must ich die sB reseten um die eingestellten werte wieder zu zurück zu setzen :-(

**Comment by foxriver76** [comment]
Checke einfach mal den Betriebsmodus, so lange dieser nicht manuell ist wird das meines Wissens nach sowieso sofort wieder zurück gesetzt.
