### ISSUE TITLE
Datenpunkt - Erklärung

### ISSUE THREAD

**Issue by SKB-CGN** [foxriver76/ioBroker.sonnen#122]
Hallo,
ich verwende den großartigen Adapter nun seit der Installation der Sonnenbatterie. Läuft prima.

Ich verstehe nur 2 Datenpunkte nicht so richtig:

powermeter.4_1.kwh_imported
powermeter.4_2.kwh_imported

Wäre super, wenn dies etwas besser beschrieben werden würde.

Vielen Dank!

**Comment by foxriver76** [comment]
Wenn jemand die Erklärung liefert, werde ich diese gerne aufnehmen. Ich selbst nutze die DPs nicht und da sie aus einem größeren JSON auf Wunsch einzeln aufgelistet wurden, fehlen mir die Details zu den einzelnen Powermeter DPs.

**Comment by SKB-CGN** [comment]
Prima, danke!

**Comment by MoerserFisch** [comment]
Hallo,

powermeter.4_1.kwh_imported:
Gesamte Produktion der PV-Anlage in kWh.

powermeter.4_2.kwh_imported:
Gesamt vom Netz bezogene Energie in kWh. 

Sollte man die Batterie nachgerüstet haben, entsprechen diese Werte natürlich nicht dem realen Export der Wechselrichter, sowie realen Import seit der Installation der PV-Anlage.
Ich hoffe ich konnte das ausreichen erklären.

**Comment by SKB-CGN** [comment]
Hallo,
ich glaube, die Beschreibung passt nicht so ganz.
Bei 4_2 wäre dies am heutigen Tag, das ich 3200 Wh vom Netz importiert hätte. Wo wir aber erst 330Wh verbraucht und 6000Wh produziert haben.
