### ISSUE TITLE
Sonnen eigene Prognose

### ISSUE THREAD

**Issue by MoerserFisch** [foxriver76/ioBroker.sonnen#126]
Hallo,

ist es möglich die Prognose Daten der Sonnenbatterie auch für den IoBroker zugänglich zu machen? Zum Beispiel:" voraussichtliche Produktion morgen in kWh". Währe sehr praktisch um Lasten intelligent zu schalten, oder auch um Diagramme in der VIS darzustellen.

Vielen Dank.

**Comment by foxriver76** [comment]
Ich kann bei Gelegenheit mal schauen, schätze  dass das über die lokale API nicht verfügbar ist. Falls du dazu bereits nähere Infos hast wäre das hilfreich.
