### ISSUE TITLE
aus externen Netzwerk

### ISSUE THREAD

**Issue by c6786** [foxriver76/ioBroker.sonnen#127]
Hallo,
funktioniert der Adapter auch wenn man in einem fremden Netzwerk mit dem Raspberry ist? (Also über Internet)

**Comment by foxriver76** [comment]
Der Adapter sendet Http Requests an die angegebene IP-Adresse. Wie diese zu erreichen ist, ist dem Adapter egal. Ist eine Sache deines Netzwerks.
