### ISSUE TITLE
Datenpunkt Export

### ISSUE THREAD

**Issue by SKB-CGN** [foxriver76/ioBroker.sonnen#134]
Hallo,
lässt sich auch irgendwie herausfinden, wieviel von der Batterie exportiert wurde?

Ich weiss, das es den Datenpunkt `sonnen.0.status.gridFeedIn` gibt. Dies ist aber immer nur der momentane Wert.
Ich würde gerne wissen, wie man an den Überschuss der Anlage kommt.

Vielen Dank!

**Comment by foxriver76** [comment]
Alternativ sollte sourceanalytix genau für sowas da sein. Falls ich in der API einen solchen Datenpunkt finde, baue ich diesen gerne ein, aber solche Berechnungen durchführen, dafür gibt es schon andere Adapter die das als Kernkompetenz haben.

**Comment by CharlesPerley** [comment]
da die sonnenBatterie nicht am Netz übergabe punkt misst sind die daten dazu nicht wirklich nutzbar weil z.b. eigenverbauch, nachladen der hohen selbsentladung bei mir 8-9% am tag bei der anzeige fehlen.
