### ISSUE TITLE
8080 port stopped working on my Sonnen Battery

### ISSUE THREAD

**Issue by kskenyon** [foxriver76/ioBroker.sonnen#140]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots & Logfiles**
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version>
 - Node version: <node-version>
 - Operating system: <os-name>
 - Battery model: <battery-model>

**Additional context**

Sonnen might have discontinued the 8080 port on the Sonnen http api.  Port 80 is used now.

**Comment by foxriver76** [comment]
#152
