### ISSUE TITLE
Auth token  Sonnen API

### ISSUE THREAD

**Issue by wodyfox** [foxriver76/ioBroker.sonnen#144]
EDIT: 
I got it to connect. How? I don't know what I really did, but it works now.
There are only 2 errors: 

1. "Auth-Token provided, but could not use official API: 404 - "<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYP...."   looks like it is an API problem. I have the older eco6, not a eco8 or later.
2. "[REQUEST] <== Error: connect ECONNREFUSED 192.168.178.21:3480".  Wher can I define the port 3480?
I do not have any values in the objecttree:  sonnen/0/status for all 3 values (Consumption, production and relative SOC). Is this related to the error above?

Still do not know where to get the Auth token for my eco6 version.

Thanks
Peter
=======================================
disregard

**Describe the bug**
I'm an absolute beginner with ioBroker and coding in general...

I have the Sonnen adapter in my ioBroker installed. There is no connection (Log). I can not find the "Software integration" tab to get the token for the adapter settings. Where I have to look for?

My Sonnen battery is a eco6 (2014):
Version SPS
5.00 (435)
Kapazitaet
0100
SOC
100.0
Betriebsart
10
Watt
0
Temperatur

Thanks a lot,
Peter

**To Reproduce**
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**

**Screenshots & Logfiles**
If applicable, add screenshots and logfiles to help explain your problem.

![Adapter](https://user-images.githubusercontent.com/34555686/177542324-c3c32087-2290-45ea-b46d-22b675d5d52c.jpg)
[ioBroker Log.txt](https://github.com/foxriver76/ioBroker.sonnen/files/9054390/ioBroker.Log.txt)

**Versions:**
 - Adapter version: 1.10.0
 - JS-Controller version: <js-controller-version>
 - Node version: <node-version>
 - Operating system: <os-name>
 - Battery model: <battery-model>

**Additional context**

**Comment by foxriver76** [comment]
Sorry for the late response. I have been on vacation. 

I don't think, that ECO 6 needs an API key, so just leave it empty in Adapter config.
