### ISSUE TITLE
High amount of log warnings from adapter after sonnenBatterie firmware update to 1.7.7

### ISSUE THREAD

**Issue by Pnuts76** [foxriver76/ioBroker.sonnen#152]
**Describe the bug**
After a firmware update of my sonnenBatterie eco 8.0 from version 1.6.x to 1.7.7 I now see a lot of warning messages from the sonnen adapter (version 1.11.0). It seems that the adapter tries to connect to not (anymore) existing endpoint on the sonnenBatterie.
Requesting API seems to work fine and data is there.

**To Reproduce**
1. Open iobroker logs
2. You can see 2 WARN log entires per request intervall (see log messages below)

**Expected behavior**
Stop querying non-existing sonnenBatterie endpoint and stop to flood iobroker logs.

**Screenshots & Logfiles**
These two log entries occur with every request interval:

```
sonnen.0 | 2022-09-01 16:58:26.693 | warn | [SETTINGS] Error receiving configuration: 404 - "{\"error\":\"404 Not Found\"}"
-- | -- | -- | --
sonnen.0 | 2022-09-01 16:58:26.675 | warn | [ADDITIONAL]  Error on requesting additional endpoints: Could not request ios  endpoint: 404 - "<!DOCTYPE html>\n<html  lang=\"en\">\n<head>\n<meta http-equiv=\"Content-Type\"  content=\"text/html; charset=utf-8\"  />\n<title>sonnenBatterie</title>\n<meta  charset=\"utf-8\">\n<meta content=\"IE=edge,chrome=1\"  http-equiv=\"X-UA-Compatible\">\n<meta  content=\"width=device-width,initial-scale=1\"  name=\"viewport\">\n<link rel=\"stylesheet\" type=\"text/css\"  href=\"/error.css\">\n</head>\n<body>\n<div  class=\"wallpaper\">\n<div class=\"logo\"></div>\n<div  class=\"error\">\n<h1>Something went  wrong</h1>\n<h3>Page not found</h3>\n<h3><a  href=\"/\">Try  again</a></h3>\n</div>\n</div>\n</body>\n</html>\n"
```

**Versions:**
 - Adapter version: v1.11.0
 - JS-Controller version: 4.0.23
 - Node version: v16.17.0
 - Operating system: Debian GNU/Linux 11 (bullseye)
 - Battery model: sonnenBatterie eco 8.0 (firmware version 1.7.7.1628395)

**Additional context**
-

**Comment by Pnuts76** [comment]
Update:
My sonnenBatterie had now been downgraded to a firmware version 1.7.2.1613111 (from 1.7.7) and the error messages are gone since then.

**Comment by foxriver76** [comment]
Please put loglevel to error for now. I have some information about the api a changes now and are currently thinking about best strategies to integrate it because api of Sonnen will be changed step by step.

**Comment by skyx3** [comment]
Is it correct that with firmware 1.7.7 port 8080 is stopped?

I ask because many points are no longer provided by V2:
http://IP:8080/api/configuration
http://IP:8080/api/battery
http://IP:8080/api/setting

**Comment by foxriver76** [comment]
Yes, unfortunately some are stopped w/o replacement for now.

**Comment by oobyx** [comment]
How can install v 1.12.0 / 1.13.0 ? In IoBroker there's only 1.11.0 available.

I have the same warning in the Logfile as pnuts

**Comment by skyx3** [comment]
![grafik](https://user-images.githubusercontent.com/58375274/198815318-91426256-81f0-40ae-b697-72084bfbbf00.png)

**Comment by foxriver76** [comment]
1.13.0 is stable now

**Comment by mha1** [comment]
Should 1.13.0 have fixed the warn messages? I still get loads of "Could not request ios endpoint" warnings

Thanks  - Michael

**Comment by oobyx** [comment]
@skyx3 - Thanks! 

But the "Could not request ios endpoint" messages in the log are still exists :/

**Comment by 1of4** [comment]
Hello,

same problem here:

[ADDITIONAL] Error on requesting additional endpoints: Could not request ios endpoint: 404 - "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n<title>sonnenBatterie</title>\n<meta charset=\"utf-8\">\n<meta content=\"IE=edge,chrome=1\" http-equiv=\"X-UA-Compatible\">\n<meta content=\"width=device-width,initial-scale=1\" name=\"viewport\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"/error.css\">\n</head>\n<body>\n<div class=\"wallpaper\">\n<div class=\"logo\"></div>\n<div class=\"error\">\n<h1>Something went wrong</h1>\n<h3>Page not found</h3>\n<h3><a href=\"/\">Try again</a></h3>\n</div>\n</div>\n</body>\n</html>\n"

Software version of the Batterie:

1.7.7.1742029

**Comment by foxriver76** [comment]
Mit Software Version 1.8.7 kommen die Endpunkte zurück, der Inverter liefert nun allerdings andere Daten als vorher. 
![Bildschirmfoto von 2022-12-12 10-54-52](https://user-images.githubusercontent.com/25484431/207015743-5c08e313-a4e4-4fd1-8c0b-100af5abfa73.png)

Hier benötige ich Feedback was interessant ist hiervon.
