### ISSUE TITLE
IP-Adresse sB

### ISSUE THREAD

**Issue by CharlesPerley** [foxriver76/ioBroker.sonnen#157]
Hallo,

toll wäre es wenn die IP-Adreesen info der sB aus dem Setup des adapters mit einem datenpunkt unter info übernommen würde. damit müste mann die adresse nur an einer stelle ändern und könnt scripte auch leichter teilen weil dann die IP direkt aud der adapter config zur verfügung stehen würde 
auch bei wechsel der IP müste dann nur an einer stelle geändert werden

Vielen dank im vorraus !!

**Comment by foxriver76** [comment]
I don’t like to outsource config in states you can get the system adapter object and read ip from their in scripts.
