### ISSUE TITLE
An additional API endpoint with lots of interesting stuff ;-)

### ISSUE THREAD

**Issue by EmPeWe** [foxriver76/ioBroker.sonnen#16]
Maybe you should have a look at `http://<IP-OF-YOUR-SONNEN-BATTERY>:8080/api/configuration`

**Comment by foxriver76** [comment]
Lots of information there, but could you please point out, which of them are of interest for the user?

**Comment by EmPeWe** [comment]
In my case, it's not the mostly static values but the additional components, the battery is capable of managing. Have you heard of sonnenPlug, sonnenCharger or sonnenHeater. There's an "operating mode" which can be logged. I'm also using the sonnenFlat, which is interesting for some of the users.
But let the users decide for themselves, which information is interesting and which is not.
In addition, there's another API at my.sonnen.de which is probably worth to have a closer look...

**Comment by foxriver76** [comment]
my.sonnen.de is depenend on an active internet connection. Basically I want to avoid this.
For the `configuration` endpoint I could at least store the JSON string in a state. If you have specific data which is of interest for you, I can also create some states. But for most of the data it won't make sense from my point of view.

I've heard of the smart home devices by sonnen, but haven't had a closer look at them until now.
