### ISSUE TITLE
Seit 1.12.1 Datenpunkte von Powermeter verändert

### ISSUE THREAD

**Issue by DerDoubleD** [foxriver76/ioBroker.sonnen#190]
**Describe the bug**
Seit 1.12.1 sind die Datenpunkte von Powermeter verändert.
Vorher 4_1 und 4_2 jetzt 0 und 1

**To Reproduce**
...

**Expected behavior**
Siehe oben bzw Screenshot

**Screenshots & Logfiles**
![image](https://user-images.githubusercontent.com/47006370/198517736-ef5e69b4-79be-4e0d-b8b7-5217fa14773d.png)

**Versions:**
 - Adapter version: 1.12.1
 - JS-Controller version: aktuell
 - Node version: aktuell
 - Operating system: linux
 - Battery model: Eco8

**Additional context**
...

**Comment by foxriver76** [comment]
Wie bereits mehrfach erwähnt, hat Sonnen die API v1 restlos abgeschalten, daher kann der Adapter derzeit nicht vollständig die Daten wie in der Vergangenheit auslesen. Der Powermeter Endpunkt wurde von v1 auf v2 migriert, dass sich dadurch ein Break in der Struktur ergibt war mir nicht bewusst, wobei sich das auch nur in einer anderen Versionsnummer des Adapters geäußert hätte. Also bitte einfach 4_1 4_2 löschen und die neuen DPs nutzen.
