### ISSUE TITLE
Frage zu den warn Meldungen

### ISSUE THREAD

**Issue by Titanflex91** [foxriver76/ioBroker.sonnen#191]
Hallo,

ich bekomme seit neustem diese Meldungen 

![image](https://user-images.githubusercontent.com/86373759/198875455-56dbd86f-77d0-43d0-a2b7-1c4fb32c3dcf.png)

Was ist hier der Fehler ?

**Comment by foxriver76** [comment]
Die alte API wurde von Sonnen abgeschaltet, ist ein API Token in den Adapter Einstellungen hinterlegt?

**Comment by Titanflex91** [comment]
Ja die API ist hinterlegt. Sogar von der Sonnenbatterie direkt

**Comment by GhostDogg77** [comment]
![image](https://user-images.githubusercontent.com/117315457/199596200-1a84b2fa-a5c6-4e3d-8440-bb0653a5d88a.png)

Mir Geht es auch so. das Log ist voll damit.
Ich habe das JasonAPI aus der Batterie.
![image](https://user-images.githubusercontent.com/117315457/199596773-bef6a17b-8da9-4976-8806-3de6c45af799.png)

**Comment by Wondermusic** [comment]
Ich schalte mich hier mal mit dazu. Gleiches Problem - das Log läuft voll mit den oben gezeigten Meldungen.

**Comment by Titanflex91** [comment]
Also gibt es hier nun eine Lösung oder nicht?

**Comment by foxriver76** [comment]
Wenn deine Batterie auf eine Version geupdated wurde, welche die v1 API abgeschaltet hat, ist die Lösung zu warten bis sonnen die beiden Endpunkte migriert hat. Bis dahin empfehle ich das Loglevel auf Error zu stellen.

**Comment by spencer2785** [comment]
Also ich kann meine API V1 unter dem der bekannten Adresse IP:8080/api/v1/status abfragen also scheint die noch aktiviert zu sein. Token habe ich eingegeben. Aber ich bekomme trotzdem diese Warnungen:  

`


  | [ADDITIONAL]  Error on requesting additional endpoints: Could not request ios  endpoint: 404 - "<!DOCTYPE html>\n<html  lang=\"en\">\n<head>\n<meta http-equiv=\"Content-Type\"  content=\"text/html; charset=utf-8\"  />\n<title>sonnenBatterie</title>\n<meta  charset=\"utf-8\">\n<meta content=\"IE=edge,chrome=1\"  http-equiv=\"X-UA-Compatible\">\n<meta  content=\"width=device-width,initial-scale=1\"  name=\"viewport\">\n<link rel=\"stylesheet\" type=\"text/css\"  href=\"/error.css\">\n</head>\n<body>\n<div  class=\"wallpaper\">\n<div class=\"logo\"></div>\n<div  class=\"error\">\n<h1>Something went  wrong</h1>\n<h3>Page not found</h3>\n<h3><a  href=\"/\">Try  again</a></h3>\n</div>\n</div>\n</body>\n</html>\n"
-- | --



`
Ideen?

**Comment by foxriver76** [comment]
Idee: Ja der Endpunkt ist weg ab firmware 1.7.7, dass v1 Status noch existent ist kann gut sein. Lt. Inoffizieller Aussage kann es 1 - 2 Versionen dauern bis die beiden Endpunkte migriert werden.

**Comment by Titanflex91** [comment]
Ja ist das den überhaupt notwendig ?

**Comment by Titanflex91** [comment]
Wie kann ich das auf Debug Level error umstellen ? 🤔

**Comment by spencer2785** [comment]
Unter Instanzen, den die Instanz Sonnen aufklappen mit dem Pfeil rechts. Dann steht in der im rechten Drittel Info da klickst Du drauf uns wählst Fehler aus.

**Comment by Titanflex91** [comment]
Okay habe es gefunden ... allerdings nur über den Experten Modus erreichbar bzw. einstellbar

**Comment by mha1** [comment]
ich habe nach Zwangsupdate auch jede Menge `[ADDITIONAL] Error on requesting additional endpoints: Could not request ios endpoint: 404` Meldungen.

Wäre nicht eine temporäre Lösung in https://github.com/foxriver76/ioBroker.sonnen/blob/master/build/main.js die Zeile 264 `await requestIosEndpoint();` einfach vorübergehend auszukommentieren?

**Comment by mha1** [comment]
Yo

**Comment by Titanflex91** [comment]
![image](https://user-images.githubusercontent.com/86373759/202858459-958caa6a-2535-4c02-93c5-90f371005c13.png)

Nun kommen ein haufen error Meldungen.

**Comment by mha1** [comment]
das ist eigenartig. nur die eine zeile auskommentiert? und wieder aktiviert geht alles (bis auf die ` Error on requesting additional endpoints ...` log message)?

dann wäre die Holzhammermethode die log message zu unterdrücken.  Hier:

`            catch (e) {
    adapter.log.warn(`[ADDITIONAL] Error on requesting additional endpoints: ${e.message}`);
            }`

den Teil `adapter.log.warn([ADDITIONAL] Error on requesting additional endpoints: ${e.message});` auskommentieren. Dann sollten wenigstens die log Einträge weg sein.

**Comment by Titanflex91** [comment]
> das ist eigenartig. nur die eine zeile auskommentiert? und wieder aktiviert geht alles (bis auf die ` Error on requesting additional endpoints ...` log message)?
> 
> 
> 
> dann wäre die Holzhammermethode die log message zu unterdrücken.  Hier:
> 
> 
> 
> `            catch (e) {
> 
>     adapter.log.warn(`[ADDITIONAL] Error on requesting additional endpoints: ${e.message}`);
> 
>             }`
> 
> 
> 
> den Teil `adapter.log.warn([ADDITIONAL] Error on requesting additional endpoints: ${e.message});` auskommentieren. Dann sollten wenigstens die log Einträge weg sein.

Du meinst ich solle das komplett auskommentieren ?

**Comment by mha1** [comment]
ja, einfach //adapter.log.warn ...

**Comment by foxriver76** [comment]
Villt einfach den Adapter auf loglevel Error stellen wie mehrfach empfohlen, ich gebe keinen Support für Installationen die den Quellcode abgeändert haben.

**Comment by mha1** [comment]
ja, verstehe ich, ist einfacher. 

Warum nimmst Du aber die Datenpunkte, die nicht mehr in der API sind nicht raus und ggf. später, wenn sie wieder verfübgar werden wieder rein?

**Comment by DerDoubleD** [comment]
@foxriver76 
Könnte man den ios Datenpunkt nicht einfach in der Adapterkonfiguration An/Abschaltbar machen.
Laut meinem Sonnenvertreter ist noch nicht klar ob der ios wieder zurück kommt und wenn ja wann...

**Comment by mha1** [comment]
> @foxriver76 Könnte man den ios Datenpunkt nicht einfach in der Adapterkonfiguration An/Abschaltbar machen. Laut meinem Sonnenvertreter ist noch nicht klar ob der ios wieder zurück kommt und wenn ja wann...

das war mein Vorschlag. Datenpunkte die nicht mehr existieren gehören disabled  und wenn sie tatsächlich irgendwann von der Sonnen Firmware wieder bereitgestellt werden, wieder enablen.

Alternative: sich vom Adapter unabhängig machen und ein kleines Javascript in iobroker erstellen, das die Batterie API per http und token anfrägt, das JSon parsed und die Datenpunkte als user objects zur Verfügung stellt. Ist jetzt auch nicht wirklich  schwierig.

**Comment by foxriver76** [comment]
Mit Software Version 1.8.7 kommen die Endpunkte zurück, der Inverter liefert nun allerdings andere Daten als vorher. 
![Bildschirmfoto von 2022-12-12 10-54-52](https://user-images.githubusercontent.com/25484431/207015743-5c08e313-a4e4-4fd1-8c0b-100af5abfa73.png)

Hier benötige ich Feedback was interessant ist hiervon.
