### ISSUE TITLE
Objekt - Datenpunkt "Inverter"

### ISSUE THREAD

**Issue by josefholdschick** [foxriver76/ioBroker.sonnen#192]
Hallo!
Seit dem Update auf APIv2 wird der Datenpunkt "Inverter" nicht mehr ausgelesen und es erscheint bei jeder Abfrage der folgende Fehler:

Hello!
Since the update to APIv2, the data point "Inverter" is no longer read out and the following error appears with every query:

2022-10-30 18:26:47.702 | warn | [ADDITIONAL] Error on requesting additional endpoints: Could not request ios endpoint: 404 - "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n<title>sonnenBatterie</title>\n<meta charset=\"utf-8\">\n<meta content=\"IE=edge,chrome=1\" http-equiv=\"X-UA-Compatible\">\n<meta content=\"width=device-width,initial-scale=1\" name=\"viewport\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"/error.css\">\n</head>\n<body>\n<div class=\"wallpaper\">\n<div class=\"logo\"></div>\n<div class=\"error\">\n<h1>Something went wrong</h1>\n<h3>Page not found</h3>\n<h3><a href=\"/\">Try again</a></h3>\n</div>\n</div>\n</body>\n</html>\n"
-- | -- | --

Vielen Dank für die restliche Arbeit!!
Thank you for the rest of your work!!!

**Comment by josefholdschick** [comment]
API-Token ist hinterlegt!

**Comment by foxriver76** [comment]
Ja den Endpunkt gibt es aktuell nicht. Sonnen hat diesen noch nicht in die neue api migriert

**Comment by josefholdschick** [comment]
Ist durch Sonnen eine Migration des Datenpunkts geplant?

**Comment by foxriver76** [comment]
Ja

**Comment by josefholdschick** [comment]
Auf meine Anfrage bei Sonnen, wann sie die Werte des Inverters in die APIv2 portieren habe ich folgende Antwort bekommen:

Hallo Herr Holdschick,
nach Rücksprache mit Kollegen müssen allen Daten wieder verfügbar sein , wie zuvor. Ggf. können Sie auch die fehelenden daten vom Ihren System berechnen lassen. Generell geben wir zu den API Schnittstellen keinen erweiterten Support.

**Comment by foxriver76** [comment]
Das sind die Infos welche ich habe

> Hallo Moritz, 
> 
> Ich nutze den sonnen IObroker Adapter, und ich habe eine sonnenBatterie die auf einer sonnen Beta SW läuft. 
> 
> Seit dem letzen SW update sind folgende API Endpoints nicht mehr verfügbar, und der sonnen Adapter spuckt munter Warnungen aus. 
> 
> http://$/{ip}:8080/api/configuration 
> http://$/{ip}:8080/api/ios  
> http://$/{ip}:8080/api/inverter
> http://$/{ip}:8080/api/powermeter
> 
> Aktuell betrifft das nur sonnenBatterien die auf Beta SW laufen, aber der Rollout der SW version 1.7.7 steht kurz bevor. 
> 
> Der powermeter Endpoint wurde bereits in die V2 Api verschoben und wäre unter folgender URL mit Token direkt weiter benutzbar.
> 
> http://$/{ip}/api/v2/powermeter
> 
> Der Plan ist auch die ios und den inverter Endpoint in die v2 api einzuführen, das kann aber noch 1-2 SW Versionen dauern.
> 
> Der Endpoint um alle Konfigurationen abzufragen entfällt. Hier gibt es auch heute schon Ersatz in der v2 Api, aber begrenzt auf die interessanten und für smart home nutzbare Konfigurationen. 
> 
> Bitte entschuldige den direkten Kontakt per Mail, aber ich nutze den sonnen IOBroker Adapter selber und dachte diese Info wäre hilfreich für dich. 
> 
> Gruß

**Comment by foxriver76** [comment]
Mit Software Version 1.8.7 kommen die Endpunkte zurück, der Inverter liefert nun allerdings andere Daten als vorher. 
![Bildschirmfoto von 2022-12-12 10-54-52](https://user-images.githubusercontent.com/25484431/207015743-5c08e313-a4e4-4fd1-8c0b-100af5abfa73.png)

Hier benötige ich Feedback was interessant ist hiervon.

**Comment by josefholdschick** [comment]
Hallo foxriver76.
Danke für deine Nachricht.
Leider ist die (für mich) interessanteste (in der v1 noch vorhandene) Information nicht enthalten, nämlich die Leistung in Watt je Phase, die der Inverter produziert. Aber daran lässt sich wohl nichts ändern. Das müsste SONNEN machen. Nachdem Sonnen aber mittlerweile hauptsächlich einphasige Systeme verkauft haben die daran scheinbar kein Interesse mehr.
Interessant sind aber viele Punkte (Auflistung mit abnehmender Wichtigkeit [für mich]):
pac_total, tmax, ubat,
Viele Grüße und vielen Dank!

**Comment by foxriver76** [comment]
Hi, mir wurde mitgeteilt, dass die 3 phasigen Systeme symmetrisch arbeiten und man somit alle Phasen gleich belastet sind, also z. B. 3000 W sind immer 1000 W je Phase. Dass kann ich für meine eco8 auch so bestätigen.

**Comment by foxriver76** [comment]
Datenpunkte sind implementiert in Adapter Version 1.15.0, demnächst im Latest, benötigt allerdings sonnen Software Version v1.8.7 o. höher, welche zeitnah ausgerollt wird.
