### ISSUE TITLE
Anzahl Volladezyklen 

### ISSUE THREAD

**Issue by man10to** [foxriver76/ioBroker.sonnen#194]
Hallo,
seit 5 Tagen wird leider die Anzahl der Vollladezyklen auch lokal auf der SB nicht mehr angezeigt:
Bisher hatte ich das dort per IOBROKER und dem PARSER geholt.
Nun geht das nicht mehr.

Könnte man das nicht auch mit dem Adapter abholen ?

Das wäre schön ;-)

**Comment by weindler** [comment]
Ich glaube nicht, daß dies aktuell geht, denn das wird in der api 2 nicht mehr angezeigt, man findet das nur im dashboard. Vielleicht kommt das mal wieder, ist das gleiche wie mit der Batterie Gesundheit, der Datenpunkt ist auch weg in der api V2

**Comment by man10to** [comment]
schade, gibt es eine möglichkeit sich das aus dem Portal zu holen ? z.b. mit dem parser ? dazu müsste man sich irgendwie mir User und PW automatisch anmelden können, geht das da ?
Ansonsten serh schöne Arbeit;-)

**Comment by foxriver76** [comment]
1.15.1 hat die Info im State `battery.cyclecount`, benötigt wird Software Version 1.8.7
