### ISSUE TITLE
Sonnen Eclipse ROT - Auslesen der Fehlermeldung

### ISSUE THREAD

**Issue by skyx3** [foxriver76/ioBroker.sonnen#213]
**Is your feature request related to a problem? Please describe.**
nein

**Describe the solution you'd like**
Wenn die Sonnenbatterie auf Fehler schaltet (Eclipse rot) wird eine Fehlermeldung vermerkt, die über die API ausgelesen werden kann. Diese ist hier zu finden: "/api/v2/latestdata.ic_status.DC Shutdown Reason" Eine der hinterlegten Fehlergründe springt dann auf True, es kann nur ein einziger dieser Datenpunkte auf True sein. Ich konnte das intensiv testen, denn auf Grund einer fehlerhaften Firmware sprang meine SB10 etwa alle 3 Tage auf Fehler.

![grafik](https://user-images.githubusercontent.com/58375274/205149690-4bd809a5-016b-484b-912a-d6c62ddaeb31.png)

**Describe alternatives you've considered**
Ich habe mir ein Blockly gebaut das prüft ob einer der Punkte auf true springt und falls ja, dann einen virtuellen Datenpunkt mit dieser Fehlermeldung beschreibt, das klappt auch ganz gut. Allerdings denke ich wäre das im Fehlerfall eine tolle Erweiterung des Adapters für die Community. Damit steht man nicht komplett im dunkeln was mit der SB los ist.

**Comment by foxriver76** [comment]
Kann ich einbauen eclipse Starus ist ja schon drin hat die gleiche Logik.

**Comment by foxriver76** [comment]
Implementiert in v1.14.0
