### ISSUE TITLE
laufender Absturz des Adapters -kein Start mehr nach Update

### ISSUE THREAD

**Issue by dlehmann69iob** [foxriver76/ioBroker.sonnen#228]
Der Adapter lässt sich seit Version 1.15.3 nicht mehr starten.

Folgende Meldungen stehen dazu im Log.

<html>
<body>

host.homeserver | 2022-12-16 12:57:30.532 | error | instance system.adapter.sonnen.0 terminated with code 3 (NO_ADAPTER_CONFIG_FOUND)
-- | -- | -- | --
sonnen.0 | 2022-12-16 12:57:29.854 | warn | Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
sonnen.0 | 2022-12-16 12:57:29.785 | error | adapter disabled
host.homeserver | 2022-12-16 12:56:57.349 | error | instance system.adapter.sonnen.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
sonnen.0 | 2022-12-16 12:56:56.684 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
sonnen.0 | 2022-12-16 12:56:56.630 | error | Exception-Code: ERR_BAD_REQUEST: Request failed with status code 404
sonnen.0 | 2022-12-16 12:56:56.629 | error | AxiosError: Request failed with status code 404 at settle (/opt/iobroker/node_modules/iobroker.sonnen/node_modules/axios/dist/node/axios.cjs:1855:12) at Unzip.handleStreamEnd (/opt/iobroker/node_modules/iobroker.sonnen/node_modules/axios/dist/node/axios.cjs:2712:11) at Unzip.emit (node:events:525:35) at endReadableNT (node:internal/streams/readable:1359:12) at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
sonnen.0 | 2022-12-16 12:56:56.626 | error | unhandled promise rejection: Request failed with status code 404
sonnen.0 | 2022-12-16 12:56:56.625 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sonnen.0 | 2022-12-16 12:56:56.546 | warn | [ADDITIONAL] Error on requesting additional endpoints: Could not request ios endpoint: Request failed with status code 404

</body>
</html>

**Versions:**
 - Adapter version: 1.15.3
 - JS-Controller version: 4.0.23
 - Node version: 18.12.1
 - Operating system: Ubuntu 22.04
 - Battery model: sonnenBatterie 10

**Comment by foxriver76** [comment]
I have fixed the crash in 1.15.4 however please note, that the adapter beta version will only work correctly with battery software version 1.8.7 and higher
