### ISSUE TITLE
batteriepflegemodus

### ISSUE THREAD

**Issue by Farmer-cb** [foxriver76/ioBroker.sonnen#258]
hallo
gibt's es einen Datenpunkt bzw. eine Möglichkeit, anzeigen zu lassen ob die Batterie gerade im Batteriepflegemodus ist

**Comment by foxriver76** [comment]
Hi, 

ich kann grundsätzlich alle Daten hinzufügen, welche du in der API Dokumentation in deiner Batterie findest (Tab Software Integration).

Gerne dort nachschauen, ich selbst kenne den status nicht.

**Comment by Farmer-cb** [comment]
Servus
Laut Beschreibung:
![image](https://user-images.githubusercontent.com/38419234/216040263-1e4a0aaa-bbc3-4a94-9988-a07c37751d0c.png)
könnte es das sein
![image](https://user-images.githubusercontent.com/38419234/216039879-551a450c-1e70-4986-9426-6efeaf5dade3.png)

**Comment by foxriver76** [comment]
Habe den DP `battery.balanceChargeRequest`  in 1.16.0 hinzugefügt. Teste gerne ob es der richtige ist.
