### ISSUE TITLE
Prognose Daten

### ISSUE THREAD

**Issue by MoerserFisch** [foxriver76/ioBroker.sonnen#281]
Schönen guten Tag!

Ich bin gerade an einem Projekt dran bezüglich zukunftsorientiertes Laden von z.B. Boiler usw. Es währe für mich sehr interessant die prognose Daten in Form von z.B. voraussichtliche Produktion in kWh pro Tag in einem Datenpunkt wieder zu finden. Die Batterie stellt das eben von Haus aus zur Verfügung.
Währe das möglich einen Datenpunkt dafür zu erstellen?

Grüße!

**Comment by skyx3** [comment]
Wie kommst Du darauf, das gibt die API nicht her, deswegen können diese Daten auch nicht angezeigt werden. Allerdings gibt es den Adapter PVforcast, diesen verwende ich um z.B. wetterbasiertes Laden morgens automatisch zu aktivieren oder deaktivieren, je nachdem wieviel Sonne kommt.

**Comment by MoerserFisch** [comment]
Alles klar. Hatte nur gehofft, dass die API das mit ausgibt, weil die Batterie das eben auch in der Weboberfläche anbietet. Aber der von dir empfohlene Adapter macht seinen Job mit einer ausreichender Genauigkeit auch. Vielen dank für den Tipp!
