### ISSUE TITLE
Misleading state Info 

### ISSUE THREAD

**Issue by Th0mg** [foxriver76/ioBroker.sonnen#291]
**Describe the bug**
Misleading Info for status.pacTotal:

Read-only number, which represents the inverter AC 
Power in watts. If the value is **greater than 0** the battery is 
**discharging**, if **greater than zero** it is **charging**

**To Reproduce**
-

**Expected behavior**
I assume one part must be **less than** 0/zero.

**Screenshots & Logfiles**
-

**Versions:**
- 

**Additional context**
-

**Comment by foxriver76** [comment]
yes below zero has to be discharging afaik, is it just in the Documentation or somewhere else?

**Comment by Th0mg** [comment]
Hi, i saw this only in the Readme markdown.

Best regards
Thomas

Am 2. November 2023 08:20:36 MEZ schrieb Max Hauser ***@***.***>:

**Comment by foxriver76** [comment]
fixed
