### ISSUE TITLE
Es gibt im LED Status von Sonnen einen neuen Datenpunkt

### ISSUE THREAD

**Issue by weindler** [foxriver76/ioBroker.sonnen#294]
Hi, nach dem neusten Update der SB, gibt es bei mir einen neuen Datenpunkt, dieser findet sich unter latest data dieser heißt "Brightness" siehe daten vom Abruf der Latest data.

`    },
        "Eclipse Led": {
            "Blinking Red": false,
            "Brightness": 100,
            "Pulsing Green": false,
            "Pulsing Orange": false,
            "Pulsing White": true,
            "Solid Red": false
        },`

Könntest du das bitte anpassen, denn anstatt Pulse White steht jetzt im Sonnen Adapter "Brightness", danke dir und frohe Weihnachten.

**Comment by foxriver76** [comment]
mit 1.17.0?

**Comment by weindler** [comment]
sorry habe ich oben vergessen, nein mit der 1.16.0

**Comment by weindler** [comment]
habe es gerade gesehen, daß du das schon umgesetzt hast in der 1.17.0, dann teste ich das mal und falls alles gut, dann sorry für das Issue.

**Comment by foxriver76** [comment]
kein Thema, gerne Feedback geben ob alles tut.

Und dir auch frohe Weihnachten. :christmas_tree:

**Comment by weindler** [comment]
Alles gut, mit der 1.17.0 läuft es wieder, danke dir für den schnellen Support. Damit mach ich das Issue zu.
