### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by kskenyon** [foxriver76/ioBroker.sonnen#33]
It looks like the plugin is looking to connect to port 80 instead of 8080 when requesting additional endpoints.  The main endpoints work fine.  Either that or it's because of different Sonnen firmware versions.  Not sure.  Error fills up the logs.

sonnen.0 | 2020-05-15 17:40:25.203 | warn | (958) [ADDITIONAL] Error on requesting additional endpoints: RequestError: Error: connect ETIMEDOUT XX.XX.XX.XX:80

Kevin

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots & Logfiles**
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version>
 - Node version: <node-version>
 - Operating system: <os-name>
 - Battery model: <battery-model>

**Additional context**

**Comment by foxriver76** [comment]
One request correctly goes to port 80 introduced with the latest update. So I guess the error occurs at every poll?

**Comment by foxriver76** [comment]
What happens when you try to open `<battery-ip>/api/online_status` in your browser.

**Comment by foxriver76** [comment]
please try 1.5.1

**Comment by kskenyon** [comment]
It occurs every poll because I don’t have port 80 forwarded to the Sonnen. I did not know port 80 was even being used on the Sonnen. I may use port 80 for another device.

**Comment by foxriver76** [comment]
80 is standard http port ..
