### ISSUE TITLE
Sonnen Adapter is restarting every minute

### ISSUE THREAD

**Issue by RESDE** [foxriver76/ioBroker.sonnen#35]
Dear Delevopers,

I updated the adapter to the current version.
After retsarting the IOBroker log shows then after ca. 1 Minute the follwing error:

  | (26227) [START] Could not get API version... restarting in 30 seconds:  RequestError: Error: connect ETIMEDOUT 111.222.255.20:7979
-- | --

The IP address is the sonnen battery in my local network... but what kind of port is used here whereas now port can be define din the adapter settings..
Please support to get the adapter running again... I´ll need urgently the measuring datas to plot the historical datas of my PV production from the roof.
Thanks a lot.
Reiner

**Comment by foxriver76** [comment]
Upgraded from which version and which version is currently running?

**Comment by RESDE** [comment]
upgrade to 1.5.2 from hmmmh cant remeber exactly 1.0.xx

**Comment by foxriver76** [comment]
The adapter tries to detect the api version on its own. Currently, two different APIs are known and supported. At first, it tries `http://${ip}:8080/api/v1/status`, it this fails it tests `http://${ip}:7979/rest/devices/battery/M03`, so it seems like. If you turn the adapter to debug it should also show an error, why `8080` wasn't able to be detected

**Comment by RESDE** [comment]
In Debug node these error messages are coming up: 
(26557) [START] It's not 8080, because RequestError: Error: ETIMEDOUT.
Dann folgt direkt 
[START] Could not get API version... restarting in 30 seconds: RequestError: Error: connect ETIMEDOUT 111.222.255.20:7979
Actaully the power production is on so the sonnen device is running too.

**Comment by foxriver76** [comment]
Stelle mal bitte sicher, dass die IP der Batterie stimmt und dass die Batterie auch erreichbar ist z. B. mittels der App oder Web-Portal. Weißt du denn unter welchem Port die API erreichbar ist?

Falls nicht z. B. von deinem Host, falls Linux `nmap  <ip>` ausführen, dann sollten alle offenen Ports angezeigt werden.

Schaut bei `8080` z. B. so aus:
```
Starting Nmap 7.60 ( https://nmap.org ) at 2020-06-25 08:43 CEST
Nmap scan report for sonnenbatterie.fritz.box (192.168.1.75)
Host is up (0.024s latency).
Not shown: 997 filtered ports
PORT     STATE SERVICE
22/tcp   open  ssh
80/tcp   open  http
8080/tcp open  http-proxy
```

**Comment by RESDE** [comment]
Hi Max,
App funzt, webportal gerade auch nochmals überprfüt, zeigt auch live daten.
Seltsam ist aber:In der Fritzbox wird zwar die SB mit .20 adressiert aber ein klick darauf funzt nicht. Dann habe ich den port 8080 ausprobiert, kein Zugriff auf die SB.Dann nmap vom Blackberry Pi (iobroker installition) aus probiert, der Host antwortet nicht.Hat Sonnen irgendwie meine SB abgeschlossen...?
Sollen wir kurz mal telefonieren, dann können wir schneller ausporbieren woran es leigt...
Hast Du selbst auch eine SB in Benutzung?GrüßeReiner


    Am Donnerstag, 25. Juni 2020, 08:45:31 MESZ hat Max Hauser <notifications@github.com> Folgendes geschrieben:  
 
 


Stelle mal bitte sicher, dass die IP der Batterie stimmt und dass die Batterie auch erreichbar ist z. B. mittels der App oder Web-Portal. Weißt du denn unter welchem Port die API erreichbar ist?

Falls nicht z. B. von deinem Host, falls Linux nmap <ip> ausführen, dann sollten alle offenen Ports angezeigt werden.

Schaut bei 8080 z. B. so aus:
Starting Nmap 7.60 ( https://nmap.org ) at 2020-06-25 08:43 CEST
Nmap scan report for sonnenbatterie.fritz.box (192.168.1.75)
Host is up (0.024s latency).
Not shown: 997 filtered ports
PORT     STATE SERVICE
22/tcp   open  ssh
80/tcp   open  http
8080/tcp open  http-proxy

**Comment by RESDE** [comment]
Hi Max,
habe gerade nochmals nmpa mit option -Pn gemacht.
Jetzt ist der Host da, aber alle ports gefiltered....???? Habe aber an der SB Einstellung nie etwas gemacht...
Hier das Scan ergebnis:pi@raspberrypi:~ $ nmap -Pn 111.22.255.20

Starting Nmap 7.40 ( https://nmap.org ) at 2020-06-25 11:10 CEST
Nmap scan report for 111.22.255.20
Host is up.
All 1000 scanned ports on 111.22.255.20 are filtered

Nmap done: 1 IP address (1 host up) scanned in 205.64 seconds
pi@raspberrypi:~ $

GrüßeReiner

    Am Donnerstag, 25. Juni 2020, 11:12:15 MESZ hat RES <reinersmail@yahoo.de> Folgendes geschrieben:  
 
  Hi Max,
App funzt, webportal gerade auch nochmals überprfüt, zeigt auch live daten.
Seltsam ist aber:In der Fritzbox wird zwar die SB mit .20 adressiert aber ein klick darauf funzt nicht. Dann habe ich den port 8080 ausprobiert, kein Zugriff auf die SB.Dann nmap vom Blackberry Pi (iobroker installition) aus probiert, der Host antwortet nicht.Hat Sonnen irgendwie meine SB abgeschlossen...?
Sollen wir kurz mal telefonieren, dann können wir schneller ausporbieren woran es leigt...
Hast Du selbst auch eine SB in Benutzung?GrüßeReiner


    Am Donnerstag, 25. Juni 2020, 08:45:31 MESZ hat Max Hauser <notifications@github.com> Folgendes geschrieben:  
 
 


Stelle mal bitte sicher, dass die IP der Batterie stimmt und dass die Batterie auch erreichbar ist z. B. mittels der App oder Web-Portal. Weißt du denn unter welchem Port die API erreichbar ist?

Falls nicht z. B. von deinem Host, falls Linux nmap <ip> ausführen, dann sollten alle offenen Ports angezeigt werden.

Schaut bei 8080 z. B. so aus:
Starting Nmap 7.60 ( https://nmap.org ) at 2020-06-25 08:43 CEST
Nmap scan report for sonnenbatterie.fritz.box (192.168.1.75)
Host is up (0.024s latency).
Not shown: 997 filtered ports
PORT     STATE SERVICE
22/tcp   open  ssh
80/tcp   open  http
8080/tcp open  http-proxy

**Comment by foxriver76** [comment]
Hm aber was mich auch wundert ist dass du sagst es ist seit dem Adapter Upgrade.. du könntest auch nochmal eine alte Version installieren um zu sehen ob es adapterseitig ist, aber wenn der Port zu ist gibts da eigentlich nix zu holen. 

Hast du die Batterie mal neugestartet bzw wurde sie korrekt gestartet? Bei der zu der ich Zugang habe muss man oben den Knopf während des Startes für 5 Sek gedrückt halten, steht allerdings auch daneben. Nach Stromausfall ist unsere zb auch nicht erreichbar, da dann beim Start keiner das knöpf hen drückt.

**Comment by RESDE** [comment]
Hallo Max,
Danke für die Infos.Habe gestern abend nochmals an der Sb selbst einen reset gemacht (SB FI Schalter raus, dann mit dem Knopf 5 sek gehalten gemäß Anleitung).Parallel dazu habe ich im Netz mehrfach gelesen, dass die Sonnen Jungs die API klamm heimlich abgeschaltet haben. Damit wird wohl Dein/euer Adapter insgesamt nicht mehr an die Daten herankommen.Leider finde ich es eine Unverschämthet, dass der Hersteller einfach seine Produkte abschliesst ohne den Besitzern Bescheid zu geben.Könnt Ihr diesen Hinweis evtl. dick auf Eure Seite posten, damit reduziert Ihr Eure Rückfragen warum der Adapter nicht läuft... Btw: bin ich aktuell der einzige mit diesem Problem?Beste GrüßeReiner

    Am Donnerstag, 25. Juni 2020, 14:10:00 MESZ hat Max Hauser <notifications@github.com> Folgendes geschrieben:  
 
 


Hm aber was mich auch wundert ist dass du sagst es ist seit dem Adapter Upgrade.. du könntest auch nochmal eine alte Version installieren um zu sehen ob es adapterseitig ist, aber wenn der Port zu ist gibts da eigentlich nix zu holen.

Hast du die Batterie mal neugestartet bzw wurde sie korrekt gestartet? Bei der zu der ich Zugang habe muss man oben den Knopf während des Startes für 5 Sek gedrückt halten, steht allerdings auch daneben. Nach Stromausfall ist unsere zb auch nicht erreichbar, da dann beim Start keiner das knöpf hen drückt.

**Comment by foxriver76** [comment]
Kannst du mir mal die Quelle zeigen wo das steht mit API Abschaltung? Welches Modell hast du denn?

**Comment by RESDE** [comment]
Hallo Max,

Sind nur wenige Quellen... suche ich raus.
Ich habe ne Eco 8 aus dem Jahr 2017/2018.
Selbst das Anmelden lokal wie damals vom Solateur ist nicht mehr möglich..ich ahne Schlimmes😳
Grüsse
Reiner

**Comment by RESDE** [comment]
Hallo Max,
wegen der APi Abschaltung guckst Du hier:
Sonnenbatterie - Seite 2 - OpenWB Forum

| 
| 
|  | 
Sonnenbatterie - Seite 2 - OpenWB Forum


 |

 |

 |

Mehr Infos waren in FHEM Forum und anderen Beiträgen, aber die habe ich jetzt so schnell nicht wiedergefunden..
Ich habe Service Ticket bei Sonnen eingestellt und das Wiedereinschalten der API moniert... halte Dich auf dem laufenden...GrüßeReiner




    Am Freitag, 26. Juni 2020, 09:14:58 MESZ hat Max Hauser <notifications@github.com> Folgendes geschrieben:  
 
 


Kannst du mir mal die Quelle zeigen wo das steht mit API Abschaltung? Welches Modell hast du denn?
