### ISSUE TITLE
New Sonnen API and Webhooks in sonnenBatterie Version 1.4.0

### ISSUE THREAD

**Issue by tk79** [foxriver76/ioBroker.sonnen#36]
**Sonnen API in User Dashboard**
When you log in to the local Dashboard as "user" under http://your_sb_ip/dash you under "software integration" you can find a new entry "API" with a corresponding swagger style documentation and a AuthToken for your battery. Following possibilities are in the documentation:

POST /api/v2/setpoint/discharge/{watt}
Sends a discharge command to the battery

GET /api/v2/status
Gets status data for this sonnenBatterie

PUT /api/v2/configurations
Sets the value of configurations

GET /api/v2/latestdata
Gets latest data for this sonnenBatterie

POST /api/v2/setpoint/charge/{watt}
Sends a charge command to the battery

GET /api/v2/configurations/{name}
Gets the value of a given configuration

**Webhook API**
furthermore the sonnenBatterie can now send data to Webhooks in definded intervalls. 
Values for "Latest Data", "System-Status" and "Powerdata" can be sent.

**Comment by foxriver76** [comment]
good news, thank you. I will look into it

**Comment by foxriver76** [comment]
Unfortunately, different browsers are not able to open the quoted page at all. When accessing `/dash` some parts of the ui are loading, but there seems to be some major problems 

```Raven caught unhandled promise rejection: 
unhandledrejection { target: Window, isTrusted: true, promise: Promise { "rejected" }, reason: undefined, srcElement: Window, eventPhase: 0, bubbles: false, cancelable: true, returnValue: true, defaultPrevented: false, … }
vendor-99a8eb46cf3f8c68e7bcc77c8a35b7cd.js:5836:164
Raven about to send: 
Object { project: "8", logger: "javascript", platform: "javascript", request: {…}, message: "undefined", mechanism: {…}, stacktrace: {…}, fingerprint: (1) […], extra: {…}, breadcrumbs: {…}, … }
vendor-99a8eb46cf3f8c68e7bcc77c8a35b7cd.js:5836:164
Uncaught (in promise) undefined
Raven about to send: 
Object { project: "8", logger: "javascript", platform: "javascript", request: {…}, exception: {…}, transaction: "http://192.168.178.76/dash/assets/vendor-99a8eb46cf3f8c68e7bcc77c8a35b7cd.js", trimHeadFrames: 0, extra: {…}, breadcrumbs: {…}, release: "1.31.1-628461+0f7de83e", … }
vendor-99a8eb46cf3f8c68e7bcc77c8a35b7cd.js:5836:164
Raven about to send: 
Object { project: "8", logger: "javascript", platform: "javascript", request: {…}, exception: {…}, transaction: "http://192.168.178.76/dash/assets/vendor-99a8eb46cf3f8c68e7bcc77c8a35b7cd.js", trimHeadFrames: 0, extra: {…}, breadcrumbs: {…}, release: "1.31.1-628461+0f7de83e", … }
vendor-99a8eb46cf3f8c68e7bcc77c8a35b7cd.js:5836:164
```

Maybe you can provide some more information about the api, maybe also the quoted documentation.

**Comment by tk79** [comment]
Sorry for the delay, here some more details about the API. You need to login to you local SonnenBatterie Web Portal, by just calling it's IP in a browser, use the credentials provided by Sonnen. I log in as USER. Details please see the attached pdf.

For calling the API a personal token is provided under "Software-Integration". The Swagger API documentation can be called without signing in using IP/api/doc.html find a PDF also in the attachments.

[sonnenBatterieAPI.pdf](https://github.com/foxriver76/ioBroker.sonnen/files/5020897/sonnenBatterieAPI.pdf)
[sonnenBatterieScreenshosts.pdf](https://github.com/foxriver76/ioBroker.sonnen/files/5020898/sonnenBatterieScreenshosts.pdf)

**Comment by foxriver76** [comment]
Thank you. I see, basically the same information as the old API but as official api for end users. I will implement the new api as additional option in the next version.

**Comment by foxriver76** [comment]
I've added basic support for the new api. All information which are currently in the adapter and are also provided by the official API will be requested at the official API. If additional information or changing configuration is needed which can be retrieved by the official API let me know in a separate Issue.
