### ISSUE TITLE
DP Array erweitern

### ISSUE THREAD

**Issue by Farmer-cb** [foxriver76/ioBroker.sonnen#52]
Hallo
wäre es möglich das Array in den Datenpunkten

- sonnen.0.info.configuration
- sonnen.0.info.inverter
- sonnen.0.info.powerMeter

in einzelne Datenpunkte aufzulösen

**Comment by foxriver76** [comment]
Grundsätzlich ja, allerdings denke ich, dass es ziemlicher Overkill wäre. Welche Datenpunkte daraus benötigst du denn konkret?

**Comment by Farmer-cb** [comment]
Servus
mir wären folgende Werte wichtig:
aus powerMeter ->4_1 & 4_2 jeweils:

- a_l1
- a_l2
- a_l3
- v_l1_l2
- v_l2_3
- v_l3_l1
- v_l1_n
- v_l2_n 
- v_l3_n
- kwh_exported
- kwh_imported
- w_l1
- w_l2
- w_l3

aus  inverter:
i_ac1
i_ac2
i_ac3
uac1
uac2
uac3
udc
temphmi
tempbcu
temppu
pac1
pac2
pac3

**Comment by foxriver76** [comment]
Könntest mir evtl noch ne kurze Beschreibung oder Bedeutung reicht auch gerne 1 Wort jedes Wertes geben, dann kann ich das hinterlegen, macht es einfacher für andere Nutzer die Bedeutung der Werte zu verstehen. Danke

**Comment by foxriver76** [comment]
hat sich erledigt, waren selbsterklärend (hoffe ich ;-))

**Comment by Farmer-cb** [comment]
wenn du noch eine Beschreibung brauchst, einfach melden


Danke für die Arbeit
