### ISSUE TITLE
Erhalte seit heute warnmeldungen Error on requesting additional endpoints

### ISSUE THREAD

**Issue by weindler** [foxriver76/ioBroker.sonnen#54]
Seit heute fallen mir diese warnmeldungen auf.

sonnen.0 | 2021-01-25 16:50:38.840 | warn | (1573) [ADDITIONAL] Error on requesting additional endpoints: Could not  request inverter endpoint: TypeError: Cannot read property 'iac1' of  undefined
-- | -- | -- | --
sonnen.0 | 2021-01-25 16:50:33.821 | warn | (1573) [ADDITIONAL] Error on requesting additional endpoints: Could not request inverter endpoint: TypeError: Cannot

Laut Softwareversion hat sich aber an der Batterie nichts geändert. 

Gruß

**Comment by foxriver76** [comment]
Was zeigt deine Batterie denn beim Aufruf von http://${ip}:8080/api/inverter?

**Comment by weindler** [comment]
{"status":{"IOStates":{"AC_Relais1Closed":true,"AC_Relais2Closed":true,"DC1_RelaisClosed":true,"DC2_RelaisClosed":true,"OpenCollectorOutput1":false,"OpenCollectorOutput2":false,"OpenCollectorOutput3":false},"fac":"49.99","iac1":"0.39","iac2":"0.00","iac3":"0.00","ibat":"0.03","ipv":"0.00","ipv2":"0.00","mode":"connected","pac1":"-2.66","pac2":"0.00","pac3":"0.00","pac_microgrid":"0.00","pac_total":"-2.66","pbat":"3.90","phi":"0.00","ppv":"0.00","ppv2":"0.00","sac1":"88.12","sac2":"0.00","sac3":"0.00","sac_total":"88.12","status":{"Active Failure":false,"Active P(f) Active":false,"Active Pu Active":false,"BDC Communication Timeout":false,"Checking FI":false,"Checking Grid DC Offset Current":false,"Checking Grid Timing":false,"Checking Isolation Resistance":false,"Checking PU Hardware":false,"Checking Relais":false,"Checking Shutdown":false,"DcInput Config Incomplete":false,"Derating External":false,"Derating Freq too high for connect":false,"Derating Freq too low for connect":false,"Derating Frequency":false,"Derating Hardware Limit":false,"Derating Startup":false,"Derating Thermal":false,"Derating User Limit":false,"FanError Active":false,"Island Mode Active":false,"Island Mode Overload":false,"Island Mode ShortCircuit":false,"Over Temperature":false,"PU Communication Timeout":false,"Reactive Output Control Active":false,"Ready":true,"Self Test Active":false,"Startup OK":true},"status2":{"FFR_Active_status":false},"tempbdc":"20.71","temphmi":"19.00","temppu":"24.93","uac1":"226.73","uac2":"0.00","uac3":"0.00","ubat":"205.59","udc":"337.46","upv":"0.00","upv2":"0.00"}}

vielleicht war auch irgendwas mir ist es halt im log aufgefallen, im iobroker ist der iac1 auch ersichtlich mit werten

**Comment by foxriver76** [comment]
Kam die Logmeldung einmalig? Oder permanent? Falls einmalig, hat einfach bei einem Poll was geklemmt.

Puh glaube die API gibt nicht viel mehr her als das was der Adapter anbietet. Evtl versteckt sich was in `info.configuration`, `info.inverter`, `info.powermeter` states.

**Comment by weindler** [comment]
ok, danke dir kam einmalig, ich beobachte es weiter, danke das mit den ladezyklen haben sie klug gemacht, denn so wie die rechnen rechnen sie zu ihren gunsten.

**Comment by foxriver76** [comment]
Puh, also wie gesagt, vill
