### ISSUE TITLE
Frage: Software Integration > Auth. Token nicht vorhanden

### ISSUE THREAD

**Issue by Claus1985** [foxriver76/ioBroker.sonnen#56]
Hallo zusammen,

erstmal vielen Dank für den genialen Adapter. Eine Frage habe ich dazu allerdings.
Wo finde ich denn auf dem aktuellen Webportal den Punkt Software Integration?
Ich habe alles mehrfach durchsucht, finde dazu aber nichts.

Danke und Gruß,

Claus

**Comment by foxriver76** [comment]
Hallo Claus,

du musst dich auf `ip-der-batterie/dash` einloggen. Also lokal auf die Batterie gehen und ohne expliziten Port (80). Dort solltest du dich als `user` einloggen können.

beste Grüße

**Comment by Claus1985** [comment]
Mit welchem Login kann ich mich dort einwählen?

**Comment by foxriver76** [comment]
War glaube in irgendeinem PDF versteckt, @tk79 weiß es evtl. da er mich damals darauf aufmerksam gemacht hat. Ich selbst habe kein Zugriff auf ein mysonnen Account, könnte sein dass es da zu finden war.

**Comment by Claus1985** [comment]
Hab es gefunden für die 8er ist es sonnenUser3552
Muss ich dort auch Webhook API aktivieren?

**Comment by tk79** [comment]
Servus, ja die gleichen Login Infos verwende ich auch bei meiner SB eco8. Nach der Anmeldung findet sich das API Auth Token unter dem Bereich Software Integration.
Die Webhook API muss nicht aktiviert werden, das ist nur notwendig wenn die SB aktiv Daten per URL Aufruf an eine andere URL / System schicken soll. Der ioBroker Adapter holt sich die Daten selber ab.
