### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by Farmer-cb** [foxriver76/ioBroker.sonnen#63]
Servus
hab die aktuellste Version installiert (1.7.3)
bekomme den Fehler 
`Auth-Token provided, but could not use official API: 401 - "{\"error\":\"401 Unauthorized\"`
habe daraufhin einen neuen Token in der Sonnenbatterie generiert und eingetragen, aber leider mit dem selben ergebnis.

log:
`

sonnen.0 | 2021-06-06 19:03:22.486 | debug | (7659) [SETTINGS] Configuration received: {"BD_Active":"1","CM_Core_API":"1","CM_DB_Logs_Flag":"2","CM_Disable_BatterySpecialStatus":"0","CM_HourlyEventsCleanup":"0","CM_Household_Fuse_Current":"200",
-- | -- | -- | --
sonnen.0 | 2021-06-06 19:03:22.444 | debug | (7659) [DATA] &lt;== {"Apparent_output":351,"BackupBuffer":"0","BatteryCharging":false,"BatteryDischarging":true,"Consumption_Avg":495,"Consumption_W":488,"Fac":50.035999298095703,"FlowConsumptionBattery
sonnen.0 | 2021-06-06 19:03:22.444 | debug | (7659) [CONNECT] Connection successful established
sonnen.0 | 2021-06-06 19:03:22.342 | debug | (7659) [START] Started Adapter with: 192.168.xxx.yyy
sonnen.0 | 2021-06-06 19:03:22.341 | debug | (7659) [INFO] Configured polling interval: 2000
sonnen.0 | 2021-06-06 19:03:22.340 | debug | (7659) [START] 8080 API detected
sonnen.0 | 2021-06-06 19:03:22.328 | error | (7659) Auth-Token provided, but could not use official API: 401 - "{\"error\":\"401 Unauthorized\"}"
sonnen.0 | 2021-06-06 19:03:22.230 | debug | (7659) [START] Auth-Token provided... trying official API
sonnen.0 | 2021-06-06 19:03:22.230 | debug | (7659) [START] Check API
sonnen.0 | 2021-06-06 19:03:22.230 | info | (7659) [START] Starting sonnen adapter
sonnen.0 | 2021-06-06 19:03:22.219 | info | (7659) starting. Version 1.7.3 in /opt/iobroker/node_modules/iobroker.sonnen, node: v12.22.1, js-controller: 3.2.16

`

**Comment by foxriver76** [comment]
Sonnen hat glaube zwei Buttons hinzugefügt um dem Token Access read and Write zu geben. Die musst du entsprechend setzen also mindestens read.

**Comment by Farmer-cb** [comment]
oh man, wer lesen kann ist ganz klar im Vorteil
jetzt funktioniert es.

Danke für den Wink mit dem Zaunpfahl ;-)

______________________________________________________________

mfg
Büchner Christian
Dietldorf 47
93133 Burglengenfeld
Mobil: 015772476055
