### ISSUE TITLE
Info:Configuration aktualisiert sich nicht

### ISSUE THREAD

**Issue by weindler** [foxriver76/ioBroker.sonnen#70]
Sonnen Adapter 1.7.3

Alles läuft wunderbar nur das Objekt mit der Configuration wird nicht upgedatet, obwohl heute eine neue Software Version draufgekommen ist und es man auch in der Api unter dem Abruf sieht.

`http://xxx.xxx.xxx.xx:8080/api/configuration`

Da ich mir mit einem Blockly die Versionen holen will, und bei Änderung dieser Configuration ein Trigger eingestellt ist sollte das funktionieren, doch der Objekt Punkt wird nicht upgedatet.

Weitere Frage was hat das mit der legacy Api auf sich?

Danke für deine Antwort.

Gruß Weindler

**Comment by foxriver76** [comment]
Configuration wird nur bei adapter start geupdated derzeit. Kann man gerne auch regelmäßig machen.

legacy api ist nur eine andere api bei älteren modellen

**Comment by weindler** [comment]
Danke dir für die schnelle Antwort, wie könnte ich das denn machen daß die regelmäßig upgedatet wird.?

Ansonsten Top Job, Danke dafür.

**Comment by foxriver76** [comment]
Ich ändere das später und mache eine neue Version, bislang hat das config Zeug keiner gebraucht und dachte wäre sehr statisch

**Comment by weindler** [comment]
Ok, ich les mir so die Batterie Version aus, da fast bei jedem Update der Version irgendwas von Sonnen schief läuft ist das für mich schon interessant, denn dann weiß ich wann die neue version draufgekommen ist. Und kann somit auch dem "tollen" Support das erzählen daß neue Version upgedatet wurde und da wahrscheinlich wieder ein Bug verbaut ist.

Bei mir macht die Batterie zwischen 3 Uhr 40 und 3 Uhr 50 meistens einen Restart, zumindestens ist sie da eigentlich nie erreichbar. darum auch die Uhrzeit auf 4 Uhr 56 gesetzt. Derweil stoppe ich mal den Adapter und starte ihn neu, dann habe ich das Datum an dem Die Batterie upgedatet wurde. Danke hat dann keine Eile. Ich wollte nur wissen ob da vielleicht bei meiner Konfig was nicht paßt, wenn das nur bei Adapter Start abgerufen wird ist mir das klar. daß er hier keine neue Version finden kann.

**Comment by weindler** [comment]
Achtung, in der Version 1.6 auf meiner Sonnenbatterie 10 hat sich im Dash Login was geändert, man muß nun die Abfragen extra erlauben, ebenso das schreiben das war vorher nicht.

Macht man das nicht dann bekommt man einen Auth Fehler wenn man auch den richtigen Token verwendet.

`
<html><body>


sonnen.0 | 2021-07-16 17:43:52.202 | error | (5895) Auth-Token provided, but could not use official API: 401 - "{\"error\":\"401 Unauthorized\"}"
-- | -- | -- | --



</body>
</html>`

Ist mir gerade aufgefallen. Ansonsten habe ich nichts weiteres entdeckt.

**Comment by foxriver76** [comment]
> Macht man das nicht dann bekommt man einen Auth Fehler wenn man auch den richtigen Token verwendet.

Jop, war hier schon mal das Problem https://github.com/foxriver76/ioBroker.sonnen/issues/63

Da der Adapter aber notfalls auf die API ohne Token zurückgreift, erst mal nicht so wild.

Mit 1.9.3 sollte die Konfiguration nun regelmäßig aktualisiert werden.

**Comment by weindler** [comment]
Ok danke dir.
