### ISSUE TITLE
Auth-Token error

### ISSUE THREAD

**Issue by DerDoubleD** [foxriver76/ioBroker.sonnen#72]
**Describe the bug**
Ich bekomme immer wieder diesen Fehler angezeigt obwohl ich den richtigen Token eingetragen habe.

**Expected behavior**

**Screenshots & Logfiles**
sonnen.0 | 2021-08-14 01:03:29.667 | error | Auth-Token provided, but could not use official API: 401 - "{\"error\":\"401 Unauthorized\"}"
-- | -- | -- | --

**Versions:**
 - Adapter version: 1.9.4
 - JS-Controller version: neueste
 - Node version: neueste
 - Operating system: Raspian
 - Battery model: Eco8

**Additional context**

**Comment by foxriver76** [comment]
Schau mal hier https://github.com/foxriver76/ioBroker.sonnen/issues/63#issuecomment-855431055 ob es daran liegt

**Comment by DerDoubleD** [comment]
Hallo
Ich habe nochmal einen neue Token erzeugt und diesen eingetragen.
Im Moment läuft es ohne Fehler! Danke für den Hinweis mit den "Schaltern"

Eine Frage noch dazu...
Werden mit der nicht Offiziellen API weniger bzw. andere Daten ausgelesen?

Danke für den Tollen Adapter!!!

**Comment by foxriver76** [comment]
Es werden mindestens alle Daten ausgeliefert die auch ohne Token kommen. Ohne Token besteht nur die Gefahr dass Sonnen die API irgendwann abschaltet und es nur noch mit Token läuft.

**Comment by DerDoubleD** [comment]
Danke für Info!!!!
