### ISSUE TITLE
Online Check spamt Pihole Log voll.

### ISSUE THREAD

**Issue by MoerserFisch** [foxriver76/ioBroker.sonnen#76]
Moin Moin.

Ich nutze den Pihole als DNS Server in meinem Netzwerk. Durch den Query Log ist mir aufgefallen, dass der Sonnen Adapter, je nach Abfragerate sehr oft nach draußen "telefoniert". Eine Möglichkeit, die Abfragerate des Online Checks separat einzustellen oder gar auszuschalten währe wirklich praktisch.

![Capture 1](https://user-images.githubusercontent.com/91428978/134817296-a378fa11-9de1-4734-b8b9-8d5125b78fb7.PNG)
![Capture](https://user-images.githubusercontent.com/91428978/134817297-4fe22357-6fa5-4c8d-9879-f9cf2493aefc.PNG)
.

**Comment by foxriver76** [comment]
Der Adapter arbeitet rein lokal und spricht keinen Endpunkt im Internet an.

**Comment by MoerserFisch** [comment]
Das ist richtig. Die Anfrage kommt auch von der Sonnenbatterie. Dennoch fallen die Anfragen weg, wenn der Sonnen Adapter pausiert wird. Das lässt mich schlussfolgern, dass die Anfrage von dem Sonnen Adapter angestoßen wird.

**Comment by foxriver76** [comment]
Alles was der Adapter macht ist im konfigurierten Intervall Endpunkte der Batterie abzufragen, das Intervall ist bereits konfigurierbar in den Adaptereinstellungen. Wenn dieses z. B. auf 30 Sek (30000 ms) steht, wird nur alle 30 Sek eine Anfrage an die Batterie gesendet, dazwischen findet kein Online Check oder derartiges statt. Wüsste also nicht wie man da weiteren Einfluss darauf nehmen kann - zu mal das bei dir ja im Sekundentakt ist, weiß nicht ob dein Polling wirklich auf 1 Sek steht?

**Comment by MoerserFisch** [comment]
Mein Polling steht auf 1s, ich brauche so eine geringe Zeit für diverse Regelungen. Selbst wenn ich die Rate jetzt auf Standard setze, würde die Batterie immer noch alle 7s die Sonnencloud anpingen, was immernoch sehr viel ist. Deshalb währe eine entkoppelte Polling rate für den Online Check super. Oder gibt es bereits eine Möglichkeit die Abfragerate der states einzeln einzustellen?

**Comment by foxriver76** [comment]
Ah .. erinnere mich gerade an https://github.com/foxriver76/ioBroker.sonnen/issues/32. 

Ja, kann man konfigurierbar machen.

**Comment by foxriver76** [comment]
Würde es dir helfen, wenn man den onlineStatus check + state komplett entfernen kann per Konfig oder ein extra polling Intervall. Ich würde zu ersterem tendieren.
